server:
  port: 8091

eureka:
  client:
    service-url: 
      default: http://localhost:8761/eureka

spring.application.name: employee-consumer
spring:
  cloud:
    discovery:
      enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic